import { useCallback } from 'react';
import { useScrollReveal } from '../lib/useScrollReveal';

interface Branch {
  index: string;
  title: string;
  description: string;
  features: string[];
  visual: React.ReactNode;
}

// ── Branch visuals ──

function OpticalGlyph() {
  return (
    <svg viewBox="0 0 80 80" fill="none" aria-hidden="true" className="w-full h-full">
      {/* Lens */}
      <circle cx="40" cy="40" r="20" stroke="#0A0E12" strokeWidth="1.2" />
      <circle cx="40" cy="40" r="12" stroke="rgba(10,14,18,0.5)" strokeWidth="0.8" />
      <circle cx="40" cy="40" r="6" fill="#0A0E12" />
      {/* Reflection */}
      <ellipse cx="34" cy="34" rx="2.5" ry="1.5" fill="#FBFAF7" />
      {/* Scan ticks */}
      <line x1="40" y1="8" x2="40" y2="14" stroke="rgba(10,14,18,0.4)" strokeWidth="1" />
      <line x1="40" y1="66" x2="40" y2="72" stroke="rgba(10,14,18,0.4)" strokeWidth="1" />
      <line x1="8" y1="40" x2="14" y2="40" stroke="rgba(10,14,18,0.4)" strokeWidth="1" />
      <line x1="66" y1="40" x2="72" y2="40" stroke="rgba(10,14,18,0.4)" strokeWidth="1" />
    </svg>
  );
}

function RFGlyph() {
  return (
    <svg viewBox="0 0 80 80" fill="none" aria-hidden="true" className="w-full h-full">
      {/* Antenna source */}
      <circle cx="40" cy="60" r="2.5" fill="#0A0E12" />
      <line x1="40" y1="55" x2="40" y2="20" stroke="#0A0E12" strokeWidth="1" />
      {/* Concentric signal arcs */}
      <path d="M22 30 Q 40 14 58 30" stroke="rgba(10,14,18,0.7)" strokeWidth="1" fill="none" />
      <path d="M16 38 Q 40 8  64 38" stroke="rgba(180,198,210,0.7)" strokeWidth="1" fill="none" />
      <path d="M10 46 Q 40 2  70 46" stroke="rgba(180,198,210,0.4)" strokeWidth="1" fill="none" />
      {/* Frequency bars at bottom */}
      <line x1="20" y1="70" x2="20" y2="66" stroke="#0A0E12" strokeWidth="1" />
      <line x1="26" y1="70" x2="26" y2="62" stroke="#0A0E12" strokeWidth="1" />
      <line x1="32" y1="70" x2="32" y2="68" stroke="#0A0E12" strokeWidth="1" />
      <line x1="48" y1="70" x2="48" y2="64" stroke="#0A0E12" strokeWidth="1" />
      <line x1="54" y1="70" x2="54" y2="68" stroke="#0A0E12" strokeWidth="1" />
      <line x1="60" y1="70" x2="60" y2="66" stroke="#0A0E12" strokeWidth="1" />
    </svg>
  );
}

function ThermalGlyph() {
  return (
    <svg viewBox="0 0 80 80" fill="none" aria-hidden="true" className="w-full h-full">
      {/* Heatmap grid */}
      <rect x="14" y="14" width="52" height="52" rx="2" stroke="#0A0E12" strokeWidth="1" fill="none" />
      {/* Hot blobs */}
      <circle cx="30" cy="32" r="9" fill="rgba(180,198,210,0.7)" />
      <circle cx="30" cy="32" r="5" fill="rgba(10,14,18,0.5)" />
      <circle cx="50" cy="46" r="6" fill="rgba(180,198,210,0.45)" />
      <circle cx="44" cy="22" r="4" fill="rgba(180,198,210,0.3)" />
      {/* Grid lines */}
      <line x1="27" y1="14" x2="27" y2="66" stroke="rgba(10,14,18,0.08)" strokeWidth="0.5" />
      <line x1="40" y1="14" x2="40" y2="66" stroke="rgba(10,14,18,0.08)" strokeWidth="0.5" />
      <line x1="53" y1="14" x2="53" y2="66" stroke="rgba(10,14,18,0.08)" strokeWidth="0.5" />
      <line x1="14" y1="27" x2="66" y2="27" stroke="rgba(10,14,18,0.08)" strokeWidth="0.5" />
      <line x1="14" y1="40" x2="66" y2="40" stroke="rgba(10,14,18,0.08)" strokeWidth="0.5" />
      <line x1="14" y1="53" x2="66" y2="53" stroke="rgba(10,14,18,0.08)" strokeWidth="0.5" />
    </svg>
  );
}

const BRANCHES: Branch[] = [
  {
    index: 'I',
    title: 'Optical Analysis',
    description:
      'AI-assisted optical scanning detects reflective lens surfaces and suspicious visual anomalies in hotel environments.',
    features: ['Lens reflection analysis', 'OpenCV preprocessing', 'Visual anomaly detection'],
    visual: <OpticalGlyph />,
  },
  {
    index: 'II',
    title: 'RF Signal Detection',
    description:
      'Wireless frequency scanning identifies suspicious RF, Wi-Fi, and Bluetooth activity associated with hidden surveillance devices.',
    features: ['RF spectrum scanning', 'Signal pattern analysis', 'Wireless anomaly monitoring'],
    visual: <RFGlyph />,
  },
  {
    index: 'III',
    title: 'Thermal Verification',
    description:
      'Thermal sensing identifies abnormal heat signatures generated by active electronic devices.',
    features: ['Heat signature analysis', 'Thermal anomaly verification', 'Environmental monitoring'],
    visual: <ThermalGlyph />,
  },
];

const FUSION_STEPS: { label: string; sub: string }[] = [
  { label: 'Optical Detection',         sub: 'Vision-based anomaly scan' },
  { label: 'RF Verification',           sub: 'Wireless cross-check' },
  { label: 'Thermal Confirmation',      sub: 'Heat-signature audit' },
  { label: 'AI Confidence Evaluation',  sub: 'Weighted fusion logic' },
  { label: 'Verified Threat Alert',     sub: 'Dispatched to dashboard' },
];

// Pointer-tracked 3D tilt — runs entirely off React, writing to style directly.
function useTilt() {
  const onMove = useCallback((e: React.MouseEvent<HTMLElement>) => {
    const el = e.currentTarget;
    const r = el.getBoundingClientRect();
    const x = (e.clientX - r.left) / r.width  - 0.5;  // -0.5 .. 0.5
    const y = (e.clientY - r.top)  / r.height - 0.5;
    el.style.transform = `perspective(700px) rotateX(${(-y * 6).toFixed(2)}deg) rotateY(${(x * 8).toFixed(2)}deg) translateY(-4px)`;
  }, []);
  const onLeave = useCallback((e: React.MouseEvent<HTMLElement>) => {
    e.currentTarget.style.transform = '';
  }, []);
  return { onMouseMove: onMove, onMouseLeave: onLeave };
}

export default function DetectionSection() {
  const [ref, revealed] = useScrollReveal<HTMLElement>();
  const tilt = useTilt();

  return (
    <section
      ref={ref}
      id="detection"
      data-revealed={revealed}
      className="relative bg-spectra-cream-deep py-16 md:py-40 px-6 md:px-12 lg:px-20 overflow-hidden"
    >
      {/* Soft mist halo */}
      <div
        className="absolute inset-0 pointer-events-none"
        style={{
          background:
            'radial-gradient(ellipse 50% 40% at 50% 35%, rgba(214,225,232,0.55) 0%, transparent 65%)',
        }}
      />
      <div className="absolute top-0 left-6 md:left-12 lg:left-20 right-6 md:right-12 lg:right-20 h-px bg-spectra-hairline" />

      <div className="relative max-w-[1400px] mx-auto">

        {/* ── Header ── */}
        <div className="grid grid-cols-12 gap-8 mb-12 md:mb-24">
          <div className="col-span-12 lg:col-span-3">
            <div className="s-up flex items-center gap-3">
              <span className="w-6 h-px bg-spectra-ink/40" />
              <span className="font-mono text-[11px] tracking-[0.25em] uppercase bg-spectra-ink text-spectra-cream px-3 py-1.5 rounded-md font-semibold">
                04 · Detection
              </span>
            </div>
          </div>

          <div className="col-span-12 lg:col-span-9">
            <h2 className="s-up s-d1 font-editorial font-light text-spectra-ink leading-[1.05] tracking-[-0.02em] mb-6"
                style={{ fontSize: 'clamp(1.75rem, 5vw, 4rem)' }}>
              Advanced Multi-Factor<br />
              <span className="italic text-spectra-ink-soft">Threat Detection.</span>
            </h2>
            <p className="s-up s-d2 max-w-2xl text-base md:text-[17px] leading-[1.7] text-spectra-ink-mute">
              WARDEN uses layered sensor fusion and AI-assisted verification to
              identify suspicious devices with higher reliability and reduced false positives.
            </p>
          </div>
        </div>

        {/* ── Converging diagram ── */}
        <div className="relative mb-12 md:mb-24">

          {/* Verified-Detection center node */}
          <div className="s-fade s-d3 relative z-10 mx-auto mb-12 md:mb-16 w-fit">
            <div className="relative w-44 h-44 md:w-52 md:h-52">
              <span className="absolute inset-0 rounded-full border border-spectra-ink/12" />
              <span className="absolute inset-4 rounded-full border border-spectra-ink/15 bg-spectra-pearl/40" />
              <div className="absolute inset-8 rounded-full bg-spectra-pearl border border-spectra-hairline
                              shadow-[0_18px_50px_-15px_rgba(10,14,18,0.18)]
                              flex flex-col items-center justify-center spectra-pulse">
                <span className="font-mono text-[9px] tracking-[0.35em] uppercase text-spectra-ink-faint mb-1.5">
                  Verified
                </span>
                <span className="font-editorial italic text-spectra-ink text-[15px] tracking-tight">
                  Detection
                </span>
                <span className="mt-2.5">
                  <svg width="20" height="20" viewBox="0 0 20 20" fill="none" aria-hidden="true">
                    <path d="M5 10 L 9 14 L 16 7" stroke="#0A0E12" strokeWidth="1.6"
                          strokeLinecap="round" strokeLinejoin="round" />
                  </svg>
                </span>
              </div>
            </div>
          </div>

          {/* Branch-converging SVG — desktop only */}
          <svg
            className="absolute top-[160px] md:top-[180px] left-1/2 -translate-x-1/2 z-0 hidden md:block pointer-events-none"
            width="1000"
            height="100"
            viewBox="0 0 1000 100"
            fill="none"
            aria-hidden="true"
          >
            <path d="M500 10 Q 500 60 180 95" stroke="rgba(10,14,18,0.18)" strokeWidth="1" />
            <path d="M500 10 L 500 95"        stroke="rgba(10,14,18,0.18)" strokeWidth="1" />
            <path d="M500 10 Q 500 60 820 95" stroke="rgba(10,14,18,0.18)" strokeWidth="1" />
            <circle r="3" fill="rgba(10,14,18,0.88)" className="signal-dot"
              style={{ offsetPath: "path('M500 10 Q 500 60 180 95')" } as React.CSSProperties} />
            <circle r="3" fill="rgba(10,14,18,0.88)" className="signal-dot"
              style={{ offsetPath: "path('M500 10 L 500 95')", animationDelay: '-0.8s' } as React.CSSProperties} />
            <circle r="3" fill="rgba(10,14,18,0.88)" className="signal-dot"
              style={{ offsetPath: "path('M500 10 Q 500 60 820 95')", animationDelay: '-1.6s' } as React.CSSProperties} />
          </svg>

          {/* Mobile vertical connector with animated signal dots */}
          <div className="flex flex-col items-center md:hidden -mt-4 mb-4">
            {[0, 1, 2].map((i) => (
              <svg key={i} width="2" height="44" viewBox="0 0 2 44" fill="none" aria-hidden="true">
                <line x1="1" y1="0" x2="1" y2="44"
                      stroke="rgba(10,14,18,0.18)" strokeWidth="1" />
                <circle r="3" cx="1" fill="rgba(10,14,18,0.88)" className="signal-dot"
                        style={{ offsetPath: "path('M1 0 L1 44')", animationDelay: `${-i * 0.8}s` } as React.CSSProperties} />
              </svg>
            ))}
          </div>

          {/* 3 branch cards */}
          <div className="relative grid grid-cols-1 md:grid-cols-3 gap-4 md:gap-5 w-full max-w-[1100px] mx-auto">
            {BRANCHES.map((b, i) => (
              <article
                key={b.title}
                onMouseMove={tilt.onMouseMove}
                onMouseLeave={tilt.onMouseLeave}
                className={`s-up s-d${i + 4}
                            group relative bg-spectra-pearl rounded-2xl p-7 md:p-8
                            border border-spectra-hairline will-change-transform
                            transition-[transform,box-shadow,border-color] duration-300 ease-smooth
                            hover:border-spectra-mist-deep/40
                            hover:shadow-[0_22px_50px_-15px_rgba(10,14,18,0.20),0_6px_15px_-5px_rgba(10,14,18,0.08)]`}
              >
                {/* Visual + header row */}
                <div className="flex items-start justify-between mb-5">
                  <span className="font-editorial italic text-spectra-ink-faint text-[26px] leading-none tracking-tight">
                    {b.index}
                  </span>
                  <div
                    className="spectra-float w-16 h-16 opacity-90 group-hover:opacity-100 transition-opacity"
                    style={{ animationDelay: `${i * 700}ms` }}
                  >
                    {b.visual}
                  </div>
                </div>

                {/* Title */}
                <h3 className="font-editorial text-xl text-spectra-ink mb-3 tracking-tight">
                  {b.title}
                </h3>

                {/* Description */}
                <p className="text-[13.5px] leading-[1.65] text-spectra-ink-mute mb-5">
                  {b.description}
                </p>

                {/* Features */}
                <ul className="space-y-2 pt-4 border-t border-spectra-hairline">
                  {b.features.map((f) => (
                    <li key={f} className="flex items-start gap-3 text-[12.5px] text-spectra-ink-soft">
                      <span className="mt-[6px] w-1 h-1 rounded-full bg-spectra-mist-deep shrink-0" />
                      <span>{f}</span>
                    </li>
                  ))}
                </ul>
              </article>
            ))}
          </div>
        </div>

        {/* ── Fusion logic block ── */}
        <div className="s-up s-d6 relative rounded-3xl border border-spectra-hairline overflow-hidden"
             style={{ background: 'linear-gradient(180deg, #FBFAF7 0%, #F0EBE2 100%)' }}>

          <div className="px-6 md:px-12 lg:px-16 py-10 md:py-20">

            {/* Block header */}
            <div className="text-center mb-12 md:mb-16">
              <div className="inline-flex items-center gap-3 mb-5">
                <span className="w-6 h-px bg-spectra-ink/30" />
                <span className="font-mono text-[11px] tracking-[0.25em] uppercase bg-spectra-ink text-spectra-cream px-3 py-1.5 rounded-md font-semibold">
                  Fusion Logic
                </span>
                <span className="w-6 h-px bg-spectra-ink/30" />
              </div>
              <h3 className="font-editorial font-light text-spectra-ink leading-[1.1] tracking-[-0.02em] max-w-2xl mx-auto"
                  style={{ fontSize: 'clamp(1.35rem, 3.5vw, 2.5rem)' }}>
                Layered Sensor Fusion <span className="italic text-spectra-ink-soft">Verification.</span>
              </h3>
              <p className="mt-5 max-w-xl mx-auto text-[15px] leading-[1.65] text-spectra-ink-mute">
                Instead of relying on a single source, WARDEN validates anomalies
                through multi-factor confirmation to improve accuracy and minimise false alerts.
              </p>
            </div>

            {/* Vertical flow */}
            <ol className="relative max-w-xl mx-auto">
              {/* Vertical rail */}
              <span className="absolute left-[26px] top-4 bottom-4 w-px bg-spectra-ink/15" />

              {FUSION_STEPS.map((step, i) => (
                <li key={step.label} className={`s-slide s-d${i + 3} relative flex items-start gap-6 pb-8 last:pb-0`}>
                  {/* Node */}
                  <div className="relative shrink-0 z-10">
                    <span className="block w-[52px] h-[52px] rounded-full bg-spectra-pearl border border-spectra-ink/30
                                     flex items-center justify-center font-mono text-[13px] tracking-[0.15em] text-spectra-ink">
                      {String(i + 1).padStart(2, '0')}
                    </span>
                  </div>

                  {/* Text */}
                  <div className="pt-2">
                    <p className="font-editorial text-[24px] md:text-[28px] tracking-tight text-spectra-ink leading-tight">
                      {step.label}
                    </p>
                    <p className="mt-2 font-mono text-[12px] tracking-[0.25em] uppercase text-spectra-ink-faint">
                      {step.sub}
                    </p>
                  </div>

                  {/* Arrow indicator on the last item */}
                  {i === FUSION_STEPS.length - 1 && (
                    <span className="absolute -right-2 top-[16px] w-2.5 h-2.5 rounded-full bg-spectra-ink animate-pulse" />
                  )}
                </li>
              ))}
            </ol>
          </div>
        </div>

        {/* ── Closing line ── */}
        <p className="s-fade s-d8 max-w-3xl mx-auto mt-20 text-center font-editorial italic text-spectra-ink-soft text-lg md:text-xl leading-[1.5]">
          By combining computer vision, wireless analysis, and thermal sensing,
          WARDEN delivers a more reliable and scalable approach to intelligent hospitality security.
        </p>
      </div>
    </section>
  );
}
